(function(){'use strict';
const $=id=>document.getElementById(id),backup=SubtitleLogBackup,prefix='subtitle-v29:'+SubtitleConnection.url+':';let current=null,request=0,pending=[],deleting=false;
function label(r){const id=r.roomId||r.scope.slice(prefix.length).replace(/:log-backup$/,'');return (r.roomName||(id==='practice'?'練習用':id)||'ルーム')+' ／ '+new Date(r.startedAt).toLocaleString('ja-JP');}
async function show(){const generation=++request;current=null;$('export').disabled=true;$('delete-selected').disabled=true;$('content').textContent='保存ログを選択してください。';$('details').textContent='';const key=$('saved-logs').value;if(!key)return;
 try{const r=await backup.read(key);if(generation!==request)return;if(!r||!r.scope.startsWith(prefix))throw Error('ログが見つかりません');current=r;$('content').textContent=backup.text(r).replace(/^\ufeff/,'')||'表示済み字幕はありません。';$('details').textContent='開始：'+new Date(r.startedAt).toLocaleString('ja-JP')+' ／ 最終保存：'+new Date(r.savedAt||r.updatedAt).toLocaleString('ja-JP')+' ／ '+(r.entries||[]).length+'件';$('export').disabled=false;$('delete-selected').disabled=false;$('status').textContent='';}catch(e){if(generation===request)$('status').textContent='ログを読み出せませんでした。'+e.message;}}
async function refresh(){try{const old=$('saved-logs').value,rows=await backup.list(prefix);$('saved-logs').replaceChildren(new Option('保存ログを選択',''));for(const r of rows)$('saved-logs').add(new Option(label(r),r.key));if([...$('saved-logs').options].some(o=>o.value===old))$('saved-logs').value=old;$('delete-all').disabled=!rows.length;$('status').textContent=rows.length?'':'このブラウザに保存されたログはありません。';await show();}catch(e){$('status').textContent='保存ログを読み込めませんでした。'+e.message;}}
async function prepareDeletion(all){try{const rows=await backup.list(prefix),targets=all?rows:rows.filter(r=>r.key===current?.key);if(!targets.length)throw Error('削除対象のログがありません。一覧を更新してください。');pending=targets.map(r=>r.key);$('delete-description').textContent=all?'この端末に保存された以下の'+targets.length+'件のログを削除します。':'選択した以下のログを削除します。';$('delete-targets').replaceChildren();for(const r of targets){const li=document.createElement('li');li.textContent=label(r);$('delete-targets').appendChild(li);}$('delete-error').textContent='';$('delete-dialog').showModal();}catch(e){$('status').textContent=e.message;}}
$('saved-logs').onchange=show;$('refresh').onclick=refresh;$('export').onclick=()=>{if(current)try{backup.download(current);}catch(e){$('status').textContent='TXTを書き出せませんでした。'+e.message;}};
$('delete-selected').onclick=()=>prepareDeletion(false);$('delete-all').onclick=()=>prepareDeletion(true);
$('delete-cancel').onclick=()=>{if(!deleting)$('delete-dialog').close();};$('delete-dialog').addEventListener('cancel',e=>{if(deleting)e.preventDefault();});$('delete-dialog').addEventListener('close',()=>{pending=[];});
$('delete-confirm').onclick=async()=>{if(deleting||!pending.length)return;deleting=true;$('delete-confirm').disabled=true;$('delete-cancel').disabled=true;try{const count=await backup.remove(prefix,[...pending]);$('delete-dialog').close();await refresh();$('status').textContent=count+'件の保存ログを削除しました。';}catch(e){$('delete-error').textContent='削除できませんでした。'+e.message;}finally{deleting=false;$('delete-confirm').disabled=false;$('delete-cancel').disabled=false;}};
refresh();
})();
